Show package link to Github and number of stars in nav bar
dbt-labs/hub.getdbt.com pull request #1801
Opened 2022-08-25 11:11 UTC by b-per

POC related to #1724 but with a different approach. Feel free to just close it if we don't want to implement it.

The link to dbt-core's repo in GitHub is removed from the main page but it is replaced by links to individual packages, showing the number of stars for each package.

In that case, the key difference between the link in the nav bar and the link in the body is that the nav bar points to the main/master branch when the body points to the actual branch the user has selected.

### Main page
![image](https://user-images.githubusercontent.com/8754100/186649294-be07dc60-c3a5-446e-8bb9-d373799fe5b6.png)

### Package page
![image](https://user-images.githubusercontent.com/8754100/186649431-7cb3ac8d-499f-41e6-8297-0241c7f58d7f.png)

2022-08-25 14:35 UTC, dbeatty10 requested changes

2022-08-25 14:35 UTC, dbeatty10 commented on source/_nav.erb
> +		<% end %>
This approach looks good to me.

The key thing we'd need to do is handle the case where `version._source.url` doesn't conform to the expected pattern. e.g., handle `nil` values or strings that don't split on `/` like we'd expect.

2022-08-25 20:01 UTC, b-per commented
I have added checks on the URL before showing the `<div>`

2022-08-25 21:54 UTC, dbeatty10 commented
@b-per did you push your latest commit(s)?

I'm only seeing a single commit:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/44704949/186775807-25487c7d-9eb8-4b81-81dd-cbadf9bc2815.png">

2022-08-26 02:23 UTC, joellabes commented
@b-per i love this! 

I wonder whether it should instead go 
![Screen Shot 2022-08-26 at 1 31 03 PM](https://user-images.githubusercontent.com/7335046/186797400-abfcc398-4340-4cda-a1f7-71d4e67b5a22.png)

The get started button is "get started with packages in general", and I suspect that the name of the repo right beside it would imply that it's "get started with dbt_expectations"

2022-08-26 07:18 UTC, b-per commented
@dbeatty10: My bad, I tried to push it yesterday but it got stuck and I didn't realize. I pushed it now

@joellabes: It makes sense! I have moved it across to the header of the package

![image](https://user-images.githubusercontent.com/8754100/186845164-a7c2afb8-6149-4231-8535-006e1fe61014.png)

2022-08-26 13:18 UTC, dbeatty10 approved these changes
Awarding 436 GitHub Stars ⭐ for you @b-per 🤩

2022-08-26 13:18 UTC, dbeatty10 commented on source/package.template.html.erb
> +              <% if is_valid_github_url(version._source.url) %>
This check is awesome.

I am still a little bit worried about a case where the full path of `version._source.url` isn't defined. But further down the code, it's already accessing that same reference without any checks, so we'll let it fly:
```
(<a href="<%= version._source.url %>">View on GitHub</a>)
```

2022-08-26 13:31 UTC, merged