Remove redundant packages saras
dbt-labs/hub.getdbt.com pull request #2701
Opened 2023-09-08 03:32 UTC by saras-daton

Deleted redundant packages which are sitting in DBT Hub.

2023-09-08 03:38 UTC, saras-daton commented
@dbeatty10 can you please help here in merging this? Have removed the redundant packages sitting in DBT Hub in this PR.

2023-09-11 03:29 UTC, joellabes requested changes
@saras-daton happy to add these to the blocklist, but please restore the deleted files in the `data/packages` directory - if anyone is still using the packages then removing from the Hub will cause their job to error.

2023-09-12 11:35 UTC, EarthBreeze commented
Hi @joellabes , intentionally removed the directories as those had some bugs and we are releasing them as new packages from now onwards. As of now, we dont want anyone to use those packages. If anyone is using also, we want them to reach out to our CS and we will help them out.

2023-09-18 09:54 UTC, joellabes approved these changes

2023-09-18 09:54 UTC, merged